#!/bin/sh
#
# Note: this is a sample and will not be run as is.

feh --bg-scale /usr/share/backgrounds/bg.png &
redshift -l 49.23:7.05 -t 5500:2500 -b 1.0:0.8 &
pactl set-sink-volume 0 '0%' &

export XKB_DEFAULT_LAYOUT=de
export XKB_DEFAULT_VARIANT=neo
export XKB_DEFAULT_OPTIONS=compose:ralt

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -d -x &

dunst &
