variables:
  level1fg: magenta
  level1bg: green
  level2fg: magenta
  level2bg: green
  level3fg: magenta
  level3bg: green
  level4fg: magenta
  level4bg: green
  level1fgalt: magenta
  level1bgalt: green
plugins:
  parsers:
    - themer.ColorParser
  activators:
    - wallpaper.WallpaperActivator
files:
  fish.tpl: config.fish
  powerline.tpl: colors.json
  chrome.tpl: manifest.json
